### ISSUE TITLE
Add spaces between headings and numbers

### ISSUE THREAD

**Issue by show0k** [hmarr/gitbook-plugin-numbered-headings#1]
Hi,
Thanks for your plugin!
By default numbers are a bit too close to the heading text
![default](https://cloud.githubusercontent.com/assets/3891499/14290272/ab3118d8-fb5e-11e5-9a7b-61832ca95ba1.png)

I tried your CSS snippet on the README but the width does not adapt to the heading depth, which cause (too) big spaces for top level, and overlap for h4 and h5.
![h1](https://cloud.githubusercontent.com/assets/3891499/14290818/e7be003e-fb60-11e5-8fa0-3bd8a22aa549.png)
![h4](https://cloud.githubusercontent.com/assets/3891499/14290821/e91ff400-fb60-11e5-9ca5-70495c038b97.png)

Any idea how to solve it ?

**Comment by hmarr** [comment]
This should be pretty dependent on your CSS - the amount of space will be affected by the font you're using, the font size, letter spacing, etc.

I imagine you'd be able to apply per-level spacing by splitting the example CSS into separate blocks for each level, e.g.:

``` css
h1:before, h2:before, h3:before {
  color: #aaa;
  width: 40px;
}

h4:before, h5:before {
  color: #aaa;
  width: 60px;
}
```
